
services:

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/var/www/frontend:ro
      - ./backend/public:/var/www/backend/public:ro
    depends_on:
      - php
    networks:
      - eldorashop

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    networks:
      - eldorashop

  mysql:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eldorashop
      MYSQL_USER: eldorashop
      MYSQL_PASSWORD: eldorashop
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eldorashop

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - eldorashop

  node:
    image: node:20
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - "5173:5173"  # pour Vite ou "3000:3000" pour create-react-app
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - eldorashop


volumes:
  db_data:

networks:
  eldorashop:
